version: '3.8'

services:
  pbb-admin-panel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    environment:
      - ENVIRONMENT=local
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
